module.exports = {
    SHOPIFY_PRODUCTS : 'SHOPIFY_PRODUCTS',
    SHOPIFY_ORDERS : 'SHOPIFY_ORDERS',
    VTEX_PRODUCTS : 'VTEX_PRODUCTS',
    VTEX_ORDERS : 'VTEX_ORDERS',
    WOOCOMMERCE_PRODUCTS : 'WOOCOMMERCE_PRODUCTS',
    WOOCOMMERCE_ORDERS : 'WOOCOMMERCE_ORDERS',
    PRESTASHOP_PRODUCTS : 'PRESTASHOP_PRODUCTS',
    PRESTASHOP_ORDERS : 'PRESTASHOP_ORDERS',
    NOTIFICATION_MELI : 'NOTIFICATION_MELI'
}