module.exports = {
    SHOPIFY_PRODUCTS : 'SHOPIFY_PRODUCTS',
    VTEX_PRODUCTS : 'VTEX_PRODUCTS',
    WOOCOMMERCE_PRODUCTS : 'WOOCOMMERCE_PRODUCTS',
    WOOCOMMERCE_ORDERS : 'WOOCOMMERCE_ORDERS',
    PRESTASHOP_PRODUCTS : 'PRESTASHOP_PRODUCTS'
}