module.exports = {
    SHOPIFY_PRODUCTS : 'SHOPIFY_PRODUCTS',
    SHOPIFY_ORDERS : 'SHOPIFY_ORDERS',
    VTEX_PRODUCTS : 'VTEX_PRODUCTS',
    WOOCOMMERCE_PRODUCTS : 'WOOCOMMERCE_PRODUCTS',
    PRESTASHOP_PRODUCTS : 'PRESTASHOP_PRODUCTS'
}